config/routes.rb
Samson::Application.routes.draw do
  resources :projects do
    resources :jobs, only: [:index, :new, :create, :show, :destroy]

    resources :macros, only: [:index, :new, :create, :edit, :update, :destroy] do
      member { post :execute }
    end

    resources :deploys, only: [:index, :new, :create, :show, :destroy] do
      collection do
        post :confirm
        get :active
      end

      member do
        post :buddy_check
        post :pending_start
        get :changeset
      end
    end

    resources :releases, only: [:show, :index, :new, :create]

    resources :stages do
      resource :lock, only: [:create, :destroy]

      collection do
        patch :reorder
      end

      member do
        get :new_relic, to: 'new_relic#show'
        get :clone, to: 'stages#clone'
      end
    end

    resource :changelog, only: [:show]
    resources :webhooks, only: [:index, :create, :destroy]
    resource  :commit_statuses, only: [:show]
  end

  resources :streams, only: [:show]

  resources :deploys, only: [] do
    collection do
      get :active
      get :recent
    end
  end

  resource :profile, only: [:show, :update]

  get '/auth/zendesk/callback', to: 'sessions#zendesk'
  get '/auth/github/callback', to: 'sessions#github'
  get '/auth/google/callback', to: 'sessions#google'
  get '/auth/failure', to: 'sessions#failure'

  get '/jobs/enabled', to: 'jobs#enabled', as: :enabled_jobs

  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'

  resources :stars, only: [:create, :destroy]

  namespace :admin do
    resources :users, only: [:index, :update, :destroy]
    resource :projects, only: [:show]
    resources :commands, except: [:show]
    resource :lock, only: [:create, :destroy]
  end

  namespace :integrations do
    post "/travis/:token" => "travis#create", as: :travis_deploy
    post "/semaphore/:token" => "semaphore#create", as: :semaphore_deploy
    post "/tddium/:token" => "tddium#create", as: :tddium_deploy
    post "/jenkins/:token" => "jenkins#create", as: :jenkins_deploy
    post "/github/:token" => "github#create", as: :github_deploy
  end

  get '/ping', to: 'ping#show'

  root to: 'projects#index'
end

app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :project
  belongs_to :user

  has_one :deploy

  after_update { deploy.touch if deploy }

  validate :validate_globally_unlocked

  ACTIVE_STATUSES = %w[pending running cancelling].freeze

  def self.non_deploy
    includes(:deploy).where(deploys: { id: nil })
  end

  def self.pending
    where(status: 'pending')
  end

  def self.running
    where(status: 'running')
  end

  def summary
    "#{user.name} #{summary_action} against #{short_reference}"
  end

  def user
    super || NullUser.new(user_id)
  end

  def started_by?(user)
    self.user == user
  end

  def commands
    command.split(/\r?\n|\r/)
  end

  def stop!
    status!("cancelling")
    execution.try(:stop!)
    status!("cancelled")
  end

  %w{pending running succeeded cancelling cancelled failed errored}.each do |status|
    define_method "#{status}?" do
      self.status == status
    end
  end

  def run!
    status!("running")
  end

  def success!
    status!("succeeded")
  end

  def fail!
    status!("failed")
  end

  def error!
    status!("errored")
  end

  def finished?
    succeeded? || failed? || errored? || cancelled?
  end

  def active?
    pending? || running? || cancelling?
  end

  def output
    super || ""
  end

  def update_output!(output)
    update_attribute(:output, output)
  end

  def update_commit!(commit)
    update_attribute(:commit, commit)
  end

  private

  def validate_globally_unlocked
    if Lock.global.exists?
      errors.add(:project, 'is locked')
    end
  end

  def execution
    JobExecution.find_by_id(id)
  end

  def status!(status)
    update_attribute(:status, status)
  end

  def summary_action
    if pending?
      "is about to execute"
    elsif running?
      "is executing"
    elsif cancelling?
      "is cancelling an execution"
    elsif cancelled?
      "cancelled an execution"
    elsif succeeded?
      "executed"
    elsif failed?
      "failed to execute"
    elsif errored?
      "encountered an error executing"
    end
  end

  def short_reference
    if commit =~ /\A[0-9a-f]{40}\Z/
      commit[0...7]
    else
      commit
    end
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound do |error|
    flash[:error] = "Job not found."
    redirect_to root_path
  end

  before_action :authorize_deployer!, only: [:new, :create, :destroy]

  before_action :find_project, except: [:enabled]
  before_action :find_job, only: [:show, :destroy]

  def index
    @jobs = @project.jobs.non_deploy.page(params[:page])
  end

  def new
    @job = Job.new
  end

  def create
    job_service = JobService.new(@project, current_user)
    command_ids = command_params[:ids].select(&:present?)

    @job = job_service.execute!(
      job_params[:commit].strip, command_ids,
      job_params[:command].strip.presence
    )

    if @job.persisted?
      JobExecution.start_job(job_params[:commit].strip, @job)
      redirect_to project_job_path(@project, @job)
    else
      render :new
    end
  end

  def show
    respond_to do |format|
      format.html
      format.text do
        datetime = @job.updated_at.strftime("%Y%m%d_%H%M%Z")
        send_data @job.output,
          type: 'text/plain',
          filename: "#{@project.repo_name}-#{@job.id}-#{datetime}.log"
      end
    end
  end

  def enabled
    if JobExecution.enabled
      head :no_content
    else
      head :accepted
    end
  end

  def destroy
    if @job.started_by?(current_user) || current_user.is_admin?
      @job.stop!

      head :ok
    else
      head :forbidden
    end
  end

  private

  def job_params
    params.require(:job).permit(:commit, :command)
  end

  def command_params
    params.require(:commands).permit(ids: [])
  end

  def find_project
    @project = Project.find_by_param!(params[:project_id])
  end

  def find_job
    @job = @project.jobs.find(params[:id])
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
  def job_page_title
    "#{@project.name} deploy (#{@job.status})"
  end

  def job_active?
    @job.active? && (JobExecution.find_by_id(@job.id) || JobExecution.enabled)
  end

  def job_status_panel(job)
    mapping = {
      "succeeded" => "success",
      "failed"    => "danger",
      "errored"   => "warning"
    }

    status = mapping.fetch(job.status, "info")

    content = h job.summary

    if job.finished?
      content << " "
      content << content_tag(:span, job.created_at.rfc822, data: { time: datetime_to_js_ms(job.created_at) }, class: 'mouseover')
    end

    content_tag :div, content.html_safe, class: "alert alert-#{status}"
  end
end

app/views/jobs/_header.html.erb
<h1>
  <%= @project.name %>
  <div class="pull-right">
    <%= link_to "Back", project_jobs_path(@project), class: "btn btn-default" %>
  </div>
</h1>

<%= job_status_panel @job %>

app/views/jobs/_job.html.erb
<% cache job do %>
  <tr>
    <td><span class="mouseover" data-time="<%= datetime_to_js_ms(job.created_at) %>"><%= job.created_at.rfc822 %></span></td>
    <td>
      <%= link_to "#{job.user.name} executed:", project_job_path(@project, job) %>
      <pre class="pre-command"><%= job.command %></pre>
    </td>
    <td><span class="label <%= deploy_status(job.status, 'label') %>"><%= job.status.titleize %></span></td>
  </tr>
<% end %>

app/views/jobs/index.html.erb
<%= render 'projects/header', project: @project, tab: "jobs" %>

<section class="tabs">
  <table class="table">
    <thead>
      <tr>
        <th>When</th>
        <th>Who</th>
        <th>Status</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <%= render @jobs %>
    </tbody>
  </table>

  <%= link_to "Execute", new_project_job_path(@project), class: "btn btn-primary" %>
  <%= paginate @jobs %>
</section>

app/views/jobs/new.html.erb
<%= form_for [@project, @job], html: { class: "form-horizontal" } do |form| %>
  <fieldset>
    <% if @job.errors.any? %>
      <div class="row">
        <div class="col-lg-5 col-lg-offset-1 alert alert-warning">
          <p><strong>Ooops!</strong> There was an error while trying to start the job:</p>
          <ul>
            <% @job.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      </div>
    <% end %>
  </fieldset>

  <fieldset>
    <legend>Reference</legend>

    <div class="form-group">
      <%= form.label :commit, "Tag or SHA", class: "col-lg-2 control-label" %>
      <div class="col-lg-4">
        <%= form.text_field :commit, class: "form-control", autofocus: true, placeholder: "e.g. v2.1.43, master, fa0b4671" %>
      </div>
    </div>
  </fieldset>

  <fieldset>
    <legend>Commands</legend>
    <p>Select the commands you want to run when executing this job.

    <div id="commands">
      <%= collection_check_boxes(:commands, :ids, Command.for_project(@project), :id, :command) do |b| %>
        <div class="row stage-bar bar">
          <div data-id="<%= b.value %>" class="col-lg-offset-2 col-lg-2 command-checkbox">
            <%= b.check_box %>
          </div>
          <div class="col-lg-8">
            <pre data-type="textarea" class="pre-command pre-inline"><%= b.text %></pre>
          </div>
        </div>
      <% end %>
    </div>

    <hr />

    <p>Add commands which are specific to your job</p>
    <%= form.text_area :command, class: "form-control", rows: 4, value: nil, placeholder: 'cap production deploy:switch' %>
  </fieldset>

  <%= javascript_tag do %>
    $(document).ready(function() {
      $('#commands').sortable();
    });
  <% end %>

  <hr>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <button type="submit" class="btn btn-primary">Execute!</button>
      <%= link_to "cancel", project_jobs_path(@project), class: 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/jobs/show.html.erb
<% content_for :page_title, job_page_title %>

<%= breadcrumb @project, "Job ##{@job.id}" %>

<div id="header" class="stream-header">
  <%= render 'header' %>
</div>

<div class="row" id="output" data-stream-url="<%= stream_path(@job) %>">
  <div class="btn-toolbar col-md-4 col-md-offset-7 pull-right" id="output-toolbar">
    <div id="output-options" class="btn-group only-active">
      <button class="btn btn-default active" id="output-follow">Follow</button>
      <button class="btn btn-default" id="output-steady">Don't Follow</button>
      <button class="btn btn-default" id="output-grow">Expand</button>
    </div>

    <div class="pull-right only-finished">
      <button class="btn btn-default" id="output-grow-toggle">Expand</button>
      <%= link_to "Download log", project_job_path(@project, @job, format: :text), class: "btn btn-primary" %>
    </div>

    <% if current_user.is_deployer? %>
      <%= link_to "Stop", project_job_path(@project, @job), remote: true, method: :delete, class: "btn btn-danger pull-right only-active" %>
    <% end %>
  </div>
</div>

<pre id="messages" class="pre-scrollable log">
  <% unless @job.active? %>
    <% @job.output.split("\n").each do |line| %>
<%= render_log(line) %>
    <% end %>
  <% end %>
</pre>

<% if job_active? %>
  <%= javascript_tag do %>
    toggleOutputToolbar();
    startStream();
  <% end %>
<% elsif !@job.finished? %>
  <div class="alert alert-info">
    Samson is currently restarting, your job has been queued and will be resumed shortly.
  </div>

  <%= javascript_tag do %>
    function check_enabled() {
      $.ajax({
        url: "<%= enabled_jobs_path %>",
        success: function(data, status, xhr) {
          if(xhr.status == 204) {
            window.location.reload()
          }
        }
      });

      setTimeout(check_enabled, 5000);
    }

    $(document).ready(function() {
      check_enabled();
    });
  <% end %>
<% end %>