config/routes.rb
Samson::Application.routes.draw do
  resources :projects do
    resources :jobs, only: [:index, :new, :create, :show, :destroy]

    resources :macros, only: [:index, :new, :create, :edit, :update, :destroy] do
      member { post :execute }
    end

    resources :deploys, only: [:index, :new, :create, :show, :destroy] do
      collection do
        post :confirm
        get :active
      end

      member do
        post :buddy_check
        post :pending_start
        get :changeset
      end
    end

    resources :releases, only: [:show, :index, :new, :create]

    resources :stages do
      resource :lock, only: [:create, :destroy]

      collection do
        patch :reorder
      end

      member do
        get :new_relic, to: 'new_relic#show'
        get :clone, to: 'stages#clone'
      end
    end

    resource :changelog, only: [:show]
    resources :webhooks, only: [:index, :create, :destroy]
    resource  :commit_statuses, only: [:show]
  end

  resources :streams, only: [:show]

  resources :deploys, only: [] do
    collection do
      get :active
      get :recent
    end
  end

  resource :profile, only: [:show, :update]

  get '/auth/zendesk/callback', to: 'sessions#zendesk'
  get '/auth/github/callback', to: 'sessions#github'
  get '/auth/google/callback', to: 'sessions#google'
  get '/auth/failure', to: 'sessions#failure'

  get '/jobs/enabled', to: 'jobs#enabled', as: :enabled_jobs

  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'

  resources :stars, only: [:create, :destroy]

  namespace :admin do
    resources :users, only: [:index, :update, :destroy]
    resource :projects, only: [:show]
    resources :commands, except: [:show]
    resource :lock, only: [:create, :destroy]
  end

  namespace :integrations do
    post "/travis/:token" => "travis#create", as: :travis_deploy
    post "/semaphore/:token" => "semaphore#create", as: :semaphore_deploy
    post "/tddium/:token" => "tddium#create", as: :tddium_deploy
    post "/jenkins/:token" => "jenkins#create", as: :jenkins_deploy
    post "/github/:token" => "github#create", as: :github_deploy
  end

  get '/ping', to: 'ping#show'

  root to: 'projects#index'
end

app/views/shared/_alerts.html.erb
<% flash_mapping.each do |type, klass| %>
  <% if messages = flash[type] %>
    <% Array.wrap(messages).each do |message| %>
      <div class="alert alert-<%= klass %>">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= message %>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="container">
    <div class="links">

      <div class="pull-left">
        Built by Zendesk
      </div>

      <div class="pull-right">
      <% if revision %>
        <span class="sha">
          <%= link_to "https://github.com/zendesk/samson/commit/#{revision}", title: "Samson release commit", class: "sha" do %>
            <%= revision[0..7] %>
            <i class="glyphicon glyphicon-circle-arrow-right"></i>
          <% end %>
        </span>
      <% end %>
      </div>

    </div>
  </div>
</div>

app/views/shared/_github_link.html.erb
<%= link_to project.repository_homepage, class: "github", target: "_blank", title: "View repository on Github" do %>
  <i class="fa fa-github"></i>
<% end %>

app/views/shared/_header.html.erb
<div class="navbar navbar-inverse">

  <div class="container">
    <%= link_to "Samson", root_path, class: "navbar-brand" %>

    <ul class="nav navbar-nav">
      <% if current_user %>
        <li class="dropdown <%= 'active' if request.path.starts_with?('/projects') %>">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Projects <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <% current_user.starred_projects.alphabetical.each do |project| %>
              <li>
              <%= link_to project_path(project) do %>
                <span class="glyphicon glyphicon-star"></span> <%= project.name %>
              <% end %>
              </li>
            <% end %>
            <% (Project.alphabetical.to_a - current_user.starred_projects).each do |project| %>
              <li>
              <%= link_to project_path(project) do %>
                <span class="glyphicon">&nbsp;</span> <%= project.name %>
              <% end %>
              </li>
            <% end %>
          </ul>
        </li>
        <li class="<%= 'active' if current_page?(controller: '/deploys', action: 'recent') %>">
          <%= link_to "Recent Deploys", recent_deploys_path %>
        </li>
        <li class="<%= 'active' if current_page?(controller: '/deploys', action: 'active') %>">
          <%= link_to active_deploys_path do %>
            Current Deploys
            <%= content_tag(:span, Deploy.active.count, class: "badge") unless Deploy.active.count.zero? %>
          <% end %>
        </li>
      <% end %>

      <% if current_user.try(:is_admin?) %>
        <li class="dropdown <%= 'active' if request.path.starts_with?('/admin') %>">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Admin <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Projects", admin_projects_path %></li>
            <li><%= link_to "Commands", admin_commands_path %></li>
            <li><%= link_to "Users", admin_users_path %></li>
          </ul>
        </li>
      <% end %>
    </ul>

    <ul class="nav navbar-nav pull-right">
      <% if logged_in? %>
        <li class="dropdown profile">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <%= image_tag current_user.gravatar_url, class: "gravatar" %>
            <%= current_user.name %>
            <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Profile", profile_path %></li>
            <li><%= link_to "Logout", logout_path %></li>
          </ul>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_project_tabs.html.erb
<ul class="nav nav-tabs">
  <li class="<%= 'active' if active == 'overview' %>">
    <%= link_to "Overview", project_path(project) %>
  </li>
  <% if project.manage_releases? %>
    <li class="<%= 'active' if active == 'releases' %>">
      <%= link_to "Releases", project_releases_path(project) %>
    </li>
  <% end %>
  <li class="<%= 'active' if active == 'deploys' %>">
    <%= link_to "Deploys", project_deploys_path(project) %>
  </li>
  <li class="<%= 'active' if active == 'jobs' %>">
    <%= link_to "Jobs", project_jobs_path(project) %>
  </li>
  <li class="<%= 'active' if active == 'macros' %>">
    <%= link_to "Macros", project_macros_path(project) %>
  </li>
  <li class="<%= 'active' if active == 'stages' %>">
    <%= link_to "Stages", project_stages_path(project) %>
  </li>
  <li class="<%= 'active' if active == 'webhooks' %>">
    <%= link_to "Webhooks", project_webhooks_path(project) %>
  </li>
  <li class="<%= 'active' if active == 'changelog' %>">
    <%= link_to "Changelog", project_changelog_path(project) %>
  </li>
<% if current_user.is_admin? %>
  <li class="<%= 'active' if active == 'settings' %>">
    <%= link_to "Settings", edit_project_path(project) %>
  </li>
<% end %>
</ul>