config/routes.rb
Samson::Application.routes.draw do
  resources :projects do
    resources :jobs, only: [:index, :new, :create, :show, :destroy]

    resources :macros, only: [:index, :new, :create, :edit, :update, :destroy] do
      member { post :execute }
    end

    resources :deploys, only: [:index, :new, :create, :show, :destroy] do
      collection do
        post :confirm
        get :active
      end

      member do
        post :buddy_check
        post :pending_start
        get :changeset
      end
    end

    resources :releases, only: [:show, :index, :new, :create]

    resources :stages do
      resource :lock, only: [:create, :destroy]

      collection do
        patch :reorder
      end

      member do
        get :new_relic, to: 'new_relic#show'
        get :clone, to: 'stages#clone'
      end
    end

    resource :changelog, only: [:show]
    resources :webhooks, only: [:index, :create, :destroy]
    resource  :commit_statuses, only: [:show]
  end

  resources :streams, only: [:show]

  resources :deploys, only: [] do
    collection do
      get :active
      get :recent
    end
  end

  resource :profile, only: [:show, :update]

  get '/auth/zendesk/callback', to: 'sessions#zendesk'
  get '/auth/github/callback', to: 'sessions#github'
  get '/auth/google/callback', to: 'sessions#google'
  get '/auth/failure', to: 'sessions#failure'

  get '/jobs/enabled', to: 'jobs#enabled', as: :enabled_jobs

  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'

  resources :stars, only: [:create, :destroy]

  namespace :admin do
    resources :users, only: [:index, :update, :destroy]
    resource :projects, only: [:show]
    resources :commands, except: [:show]
    resource :lock, only: [:create, :destroy]
  end

  namespace :integrations do
    post "/travis/:token" => "travis#create", as: :travis_deploy
    post "/semaphore/:token" => "semaphore#create", as: :semaphore_deploy
    post "/tddium/:token" => "tddium#create", as: :tddium_deploy
    post "/jenkins/:token" => "jenkins#create", as: :jenkins_deploy
    post "/github/:token" => "github#create", as: :github_deploy
  end

  get '/ping', to: 'ping#show'

  root to: 'projects#index'
end

app/models/webhook.rb
class Webhook < ActiveRecord::Base
  has_soft_deletion default_scope: true
  validates :branch, uniqueness: { scope: [ :stage], conditions: -> { where("deleted_at IS NULL") }, message: "one webhook per (stage, branch) combination." }

  belongs_to :project
  belongs_to :stage

  def self.for_branch(branch)
    where(branch: branch)
  end
end

app/controllers/webhooks_controller.rb
class WebhooksController < ApplicationController
  before_action :authorize_deployer!
  before_action :find_project

  def index
    @webhooks = @project.webhooks
  end

  def new
    @webhooks = @project.webhooks
  end

  def create
    @project.webhooks.create!(webhook_params)

    redirect_to project_webhooks_path(@project)
  end

  def destroy
    webhook = @project.webhooks.find(params[:id])
    webhook.soft_delete!

    redirect_to project_webhooks_path(@project)
  end

  def show
    @webhook = @project.webhooks.find(params[:id])
  end

  private

  def find_project
    @project = Project.find_by_param!(params[:project_id])
  end

  def webhook_params
    params.require(:webhook).permit(:branch, :stage_id)
  end

end

app/helpers/webhooks_helper.rb
module WebhooksHelper
  def link_to_url(url)
    link_to(url, url)
  end
end

app/views/webhooks/index.html.erb
<%= render 'projects/header', project: @project, tab: "webhooks" %>

<section class="tabs">
  <p>In order to automatically trigger a deploy to a stage, add a branch &rarr; stage mapping below
  and paste in the project's webhook URL to your CI service of choice.</p>

  <dl>
    <dt>Semaphore:</dt><dd><%= link_to_url integrations_semaphore_deploy_url(@project.token) %></dd>
    <dt>Tddium:</dt><dd><%= link_to_url integrations_tddium_deploy_url(@project.token) %></dd>
    <dt>Travis:</dt><dd><%= link_to_url integrations_travis_deploy_url(@project.token) %></dd>
    <dt>Jenkins:</dt><dd><%= link_to_url integrations_jenkins_deploy_url(@project.token) %></dd>
    <dt>Github Push:</dt><dd><%= link_to_url integrations_github_deploy_url(@project.token) %></dd>
  </dl>

  <% if @webhooks.any? %>
    <h2>Webhooks mappings</h2>
    <ul>
      <% @webhooks.each do |webhook| %>
        <li><strong><%= webhook.branch %></strong> branch &rarr; <strong><%= webhook.stage.name %></strong> stage (<%= link_to "remove", project_webhook_path(@project, webhook), method: :delete %>)</li>
      <% end %>
    </ul>
  <% end %>

  <h2>Add webhook mapping</h2>
  <%= form_for :webhook, url: project_webhooks_path(@project), html: { class: "form-inline" } do |form| %>
    <div class="form-group">
      <%= form.text_field :branch, class: "form-control", placeholder: "Branch" %>
    </div>

    &rarr;

    <div class="form-group">
      <%= form.collection_select :stage_id, @project.stages, :id, :name, {}, class: "form-control" %>
    </div>

    <%= form.submit "Add webhook", class: "btn btn-primary" %>
  <% end %>
</section>