config/routes.rb
Samson::Application.routes.draw do
  resources :projects do
    resources :jobs, only: [:index, :new, :create, :show, :destroy]

    resources :macros, only: [:index, :new, :create, :edit, :update, :destroy] do
      member { post :execute }
    end

    resources :deploys, only: [:index, :new, :create, :show, :destroy] do
      collection do
        post :confirm
        get :active
      end

      member do
        post :buddy_check
        post :pending_start
        get :changeset
      end
    end

    resources :releases, only: [:show, :index, :new, :create]

    resources :stages do
      resource :lock, only: [:create, :destroy]

      collection do
        patch :reorder
      end

      member do
        get :new_relic, to: 'new_relic#show'
        get :clone, to: 'stages#clone'
      end
    end

    resource :changelog, only: [:show]
    resources :webhooks, only: [:index, :create, :destroy]
    resource  :commit_statuses, only: [:show]
  end

  resources :streams, only: [:show]

  resources :deploys, only: [] do
    collection do
      get :active
      get :recent
    end
  end

  resource :profile, only: [:show, :update]

  get '/auth/zendesk/callback', to: 'sessions#zendesk'
  get '/auth/github/callback', to: 'sessions#github'
  get '/auth/google/callback', to: 'sessions#google'
  get '/auth/failure', to: 'sessions#failure'

  get '/jobs/enabled', to: 'jobs#enabled', as: :enabled_jobs

  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'

  resources :stars, only: [:create, :destroy]

  namespace :admin do
    resources :users, only: [:index, :update, :destroy]
    resource :projects, only: [:show]
    resources :commands, except: [:show]
    resource :lock, only: [:create, :destroy]
  end

  namespace :integrations do
    post "/travis/:token" => "travis#create", as: :travis_deploy
    post "/semaphore/:token" => "semaphore#create", as: :semaphore_deploy
    post "/tddium/:token" => "tddium#create", as: :tddium_deploy
    post "/jenkins/:token" => "jenkins#create", as: :jenkins_deploy
    post "/github/:token" => "github#create", as: :github_deploy
  end

  get '/ping', to: 'ping#show'

  root to: 'projects#index'
end

app/models/stage.rb
class Stage < ActiveRecord::Base
  include Permalinkable

  has_soft_deletion default_scope: true

  belongs_to :project, touch: true

  has_many :deploys, dependent: :destroy
  has_many :webhooks, dependent: :destroy
  has_many :flowdock_flows
  has_many :new_relic_applications

  has_one :lock

  has_many :stage_commands, autosave: true
  has_many :commands,
    -> { order('stage_commands.position ASC') },
    through: :stage_commands

  default_scope { order(:order) }

  validates :name, presence: true, uniqueness: { scope: [:project, :deleted_at] }

  accepts_nested_attributes_for :flowdock_flows, allow_destroy: true, reject_if: :no_flowdock_token?
  accepts_nested_attributes_for :new_relic_applications, allow_destroy: true, reject_if: :no_newrelic_name?

  attr_writer :command
  before_save :build_new_project_command

  def self.reorder(new_order)
    transaction do
      new_order.each.with_index { |stage_id, index| Stage.update stage_id.to_i, order: index.to_i }
    end
  end

  def self.build_clone(old_stage)
    new(old_stage.attributes).tap do |new_stage|
      new_stage.flowdock_flows.build(old_stage.flowdock_flows.map(&:attributes))
      new_stage.new_relic_applications.build(old_stage.new_relic_applications.map(&:attributes))
      new_stage.command_ids = old_stage.command_ids
    end
  end

  def self.unlocked_for(user)
    where("locks.id IS NULL OR locks.user_id = ?", user.id).
    joins("LEFT OUTER JOIN locks ON \
          locks.deleted_at IS NULL AND \
          locks.stage_id = stages.id")
  end

  def self.deployed_on_release
    where(deploy_on_release: true)
  end

  def self.where_reference_being_deployed(reference)
    joins(deploys: :job).where(
      deploys: { reference: reference },
      jobs: { status: Job::ACTIVE_STATUSES }
    )
  end

  def current_deploy
    @current_deploy ||= deploys.active.first
  end

  def last_deploy
    @last_deploy ||= deploys.first
  end

  def last_successful_deploy
    @last_successful_deploy ||= deploys.successful.first
  end

  def locked?
    lock.present?
  end

  def locked_for?(user)
    locked? && lock.user != user
  end

  def current_release?(release)
    last_successful_deploy && last_successful_deploy.reference == release.version
  end

  def confirm_before_deploying?
    confirm
  end

  def create_deploy(options = {})
    user = options.fetch(:user)
    reference = options.fetch(:reference)

    deploys.create(reference: reference) do |deploy|
      deploy.build_job(project: project, user: user, command: command)
    end
  end

  def currently_deploying?
    current_deploy.present?
  end

  # The next stage for the project. If this is the last stage, returns nil.
  def next_stage
    stages = project.stages.to_a
    stages[stages.index(self) + 1]
  end

  def notify_email_addresses
    notify_email_address.split(";").map(&:strip)
  end

  def send_email_notifications?
    notify_email_address.present?
  end

  def send_flowdock_notifications?
    flowdock_flows.any?
  end

  def flowdock_tokens
    flowdock_flows.map(&:token)
  end

  def command
    commands.map(&:command).join("\n")
  end

  def command_ids=(new_command_ids)
    super.tap do
      reorder_commands(new_command_ids.reject(&:blank?).map(&:to_i))
    end
  end

  def all_commands
    command_scope = project ? Command.for_project(project) : Command.global

    if command_ids.any?
      command_scope = command_scope.where(['id NOT in (?)', command_ids])
    end

    commands + command_scope
  end

  def datadog_tags
    super.to_s.split(";").map(&:strip)
  end

  def send_datadog_notifications?
    datadog_tags.any?
  end

  def send_github_notifications?
    update_github_pull_requests
  end

  private

  def build_new_project_command
    return unless @command.present?

    new_command = project.commands.build(command: @command)
    stage_commands.build(command: new_command).tap do
      reorder_commands
    end
  end

  def reorder_commands(command_ids = self.command_ids)
    stage_commands.each do |stage_command|
      pos = command_ids.index(stage_command.command_id) ||
        stage_commands.length

      stage_command.position = pos
    end
  end

  def no_flowdock_token?(flowdock_attrs)
    flowdock_attrs['token'].blank?
  end

  def no_newrelic_name?(newrelic_attrs)
    newrelic_attrs['name'].blank?
  end

  def permalink_base
    name
  end

  def permalink_scope
    Stage.unscoped.where(project_id: project_id)
  end
end

app/models/user.rb
require 'soft_deletion'
require 'digest/md5'

class User < ActiveRecord::Base
  has_soft_deletion default_scope: true

  has_many :commands
  has_many :stars
  has_many :starred_projects, through: :stars, source: :project

  validates :role_id, inclusion: { in: Role.all.map(&:id) }

  before_create :set_token

  scope :search, ->(query) { where("name like ? or email like ?", "%#{query}%", "%#{query}%") }

  def starred_project?(project)
    starred_projects.include?(project)
  end

  def self.create_or_update_from_hash(hash)
    user = User.where(external_id: hash[:external_id].to_s).first || User.new

    # attributes are always a string hash
    attributes = user.attributes.merge(hash.stringify_keys) do |key, old, new|
      if key == 'role_id'
        if !User.exists?
          Role::SUPER_ADMIN.id
        elsif new && (user.new_record? || new >= old)
          new
        else
          old
        end
      else
        old.presence || new
      end
    end

    user.attributes = attributes
    user.save
    user
  end

  def name
    super.presence || email
  end

  def name_and_email
    "#{name} (#{email})"
  end

  def gravatar_url
    md5 = email.blank? ? "default" : Digest::MD5.hexdigest(email)
    "https://www.gravatar.com/avatar/#{md5}"
  end

  Role.all.each do |role|
    define_method "is_#{role.name}?" do
      role_id >= role.id
    end
  end

  private

  def set_token
    self.token = SecureRandom.hex
  end
end

app/controllers/stages_controller.rb
class StagesController < ApplicationController
  skip_before_action :login_users, if: :badge?
  before_action :authorize_admin!, except: [:index, :show]
  before_action :authorize_deployer!, unless: :badge?
  before_action :check_token, if: :badge?
  before_action :find_project
  before_action :find_stage, only: [:show, :edit, :update, :destroy, :clone]

  rescue_from ActiveRecord::RecordNotFound do
    if @project
      redirect_to project_path(@project)
    else
      redirect_to root_path
    end
  end

  def index
    @stages = @project.stages

    respond_to do |format|
      format.html
      format.json do
        render json: @stages
      end
    end
  end

  def show
    respond_to do |format|
      format.html do
        @deploys = @stage.deploys.includes(:stage, job: :user).page(params[:page])
      end
      format.svg do
        badge = if deploy = @stage.last_successful_deploy
          "#{badge_safe(@stage.name)}-#{badge_safe(deploy.short_reference)}-green"
        else
          "#{badge_safe(@stage.name)}-None-red"
        end

        if stale?(etag: badge)
          expires_in 1.minute, :public => true
          image = open("http://img.shields.io/badge/#{badge}.svg").read
          render text: image, content_type: Mime::SVG
        end
      end
    end
  end

  def new
    @stage = @project.stages.build(command_ids: Command.global.pluck(:id))
    @stage.flowdock_flows.build
    @stage.new_relic_applications.build
  end

  def create
    # Need to ensure project is already associated
    @stage = @project.stages.build
    @stage.attributes = stage_params

    if @stage.save
      redirect_to project_stage_path(@project, @stage)
    else
      flash[:error] = @stage.errors.full_messages

      @stage.flowdock_flows.build
      @stage.new_relic_applications.build

      render :new
    end
  end

  def edit
    @stage.flowdock_flows.build
    @stage.new_relic_applications.build
  end

  def update
    if @stage.update_attributes(stage_params)
      redirect_to project_stage_path(@project, @stage)
    else
      flash[:error] = @stage.errors.full_messages

      @stage.flowdock_flows.build
      @stage.new_relic_applications.build

      render :edit
    end
  end

  def destroy
    @stage.soft_delete!
    redirect_to project_path(@project)
  end

  def reorder
    Stage.reorder(params[:stage_id])

    head :ok
  end

  def clone
    @stage = Stage.build_clone(@stage)
    render :new
  end

  private

  def badge_safe(string)
    CGI.escape(string.gsub('&', '&amp;')).gsub('-', '&mdash;').gsub('+','%20')
  end

  def check_token
    unless params[:token] == Rails.application.config.samson.badge_token
      raise ActiveRecord::RecordNotFound
    end
  end

  def badge?
    action_name == 'show' && request.format == Mime::SVG
  end

  def stage_params
    params.require(:stage).permit(
      :name, :command, :confirm, :permalink,
      :production,
      :notify_email_address,
      :deploy_on_release,
      :datadog_tags,
      :update_github_pull_requests,
      command_ids: [],
      flowdock_flows_attributes: [:id, :name, :token, :_destroy],
      new_relic_applications_attributes: [:id, :name, :_destroy]
    )
  end

  def find_project
    @project = Project.find_by_param!(params[:project_id])
  end

  def find_stage
    @stage = @project.stages.find_by_param!(params[:id])
  end
end

app/helpers/stages_helper.rb
module StagesHelper
  def edit_command_link(command)
    admin = current_user.is_admin?
    edit_url = edit_admin_command_path(command)
    if command.global?
      title, url = if admin
        ["Edit global command", edit_url]
      else
        ["Global command, can only be edited via Admin UI", "#"]
      end
      link_to "", url, title: title, class: "edit-command glyphicon glyphicon-globe no-hover"
    elsif admin
      link_to "", edit_url, title: "Edit in admin UI", class: "edit-command glyphicon glyphicon-edit no-hover"
    end
  end
end

app/views/stages/_fields.html.erb
<fieldset>
  <div class="form-group">
    <%= form.label :name, "Name", class: "col-lg-2 control-label" %>
    <div class="col-lg-4">
      <%= form.text_field :name, class: "form-control" %>
    </div>
  </div>

  <% if form.object.persisted? %>
    <div class="form-group">
      <%= form.label :permalink, "Permalink", class: "col-lg-2 control-label" %>
      <div class="col-lg-4">
        <%= form.text_field :permalink, class: "form-control" %>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :notify_email_address, "Email addresses", class: "col-lg-2 control-label" %>
    <div class="col-lg-4">
      <%= form.text_field :notify_email_address, class: "form-control" %>
      <span class="help-block">Enter the email addresses that should be notified of new deploys, separated by <code>;</code></span>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <div class="checkbox">
        <%= form.label :confirm do %>
          <%= form.check_box :confirm %>
          Confirm before deployment
        <% end %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <div class="checkbox">
        <%= form.label :production do %>
          <%= form.check_box :production %>
          Does this stage impact production servers?
        <% end %>
      </div>
    </div>
  </div>

  <% if @project.manage_releases? %>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <div class="checkbox">
          <%= form.label :deploy_on_release do %>
            <%= form.check_box :deploy_on_release %>
            Automatically deploy new releases
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</fieldset>

<fieldset>
  <legend>Commands</legend>
  <p>Select the commands you want to run when executing this stage. Double click to edit commands.</p>

  <div id="commands">
    <%= form.collection_check_boxes(:command_ids, form.object.all_commands, :id, :command) do |b| %>
      <div class="row stage-bar bar">
        <div data-id="<%= b.value %>" class="col-lg-offset-2 col-lg-2 command-checkbox">
          <%= b.check_box %>
        </div>
        <div class="col-lg-8">
          <pre data-type="textarea" data-url="<%= admin_command_path(b.value, format: :json) %>" class="pre-command pre-inline <%= b.object.global? ? 'global' : 'local' %>"><%= b.text %></pre>
        </div>
        <%= edit_command_link(b.object) %>
      </div>
    <% end %>
  </div>

  <hr />

  <p>Add a command which is specific to your project</p>
  <%= form.text_area :command, class: "form-control", rows: 4, value: nil, placeholder: 'cap production deploy' %>
</fieldset>

<fieldset>
  <legend>Flowdock</legend>
  <p>Add the name and API token of the Flowdock flow which should be notified of deploys.</p>

  <%= form.fields_for :flowdock_flows do |flow_fields| %>
    <div class="form-group">
      <div class="col-lg-2 col-lg-offset-2">
        <%= flow_fields.text_field :name, class: "form-control", placeholder: "Flow name" %>
      </div>

      <div class="col-lg-4">
        <%= flow_fields.text_field :token, class: "form-control", placeholder: "Token" %>
      </div>

      <% if flow_fields.object.persisted? %>
        <div class="col-lg-1 checkbox">
          <%= flow_fields.check_box :_destroy if flow_fields.object.persisted? %>
          <%= flow_fields.label :_destroy, "Delete" %>
        </div>
      <% end %>
    </div>
  <% end %>
</fieldset>

<fieldset>
  <legend>New Relic</legend>
  <p>Add the name of New Relic Applications that you would like to keep of during this stages' deploys.</p>

  <%= form.fields_for :new_relic_applications do |app_fields| %>
    <div class="form-group">
      <div class="col-lg-6 col-lg-offset-2">
        <%= app_fields.text_field :name, class: "form-control", placeholder: "Application name" %>
      </div>

      <% if app_fields.object.persisted? %>
        <div class="col-lg-1 checkbox">
          <%= app_fields.check_box :_destroy if app_fields.object.persisted? %>
          <%= app_fields.label :_destroy, "Delete" %>
        </div>
      <% end %>
    </div>
  <% end %>
</fieldset>

<fieldset>
  <legend>Datadog</legend>
  <p>Add the tags that should be used when notifying Datadog of deploys. Leave empty if you don't want
  to send notifications to Datadog.</p>

  <div class="form-group">
    <div class="col-lg-6 col-lg-offset-2">
      <%= form.text_field :datadog_tags, class: "form-control", placeholder: "Datadog tags" %>
      <span class="help-block">Enter the tags that should be used on deploy events, separated by <code>;</code></span>
    </div>
  </div>
</fieldset>

<fieldset>
  <legend>Github</legend>
  <div class="col-lg-6 checkbox">
    <%= form.label :update_github_pull_requests do %>
      <%= form.check_box :update_github_pull_requests %>
      Update Pull Request after deployment
    <% end %>
  </div>
  <div class="col-lg-6 checkbox">
    <%= form.label :use_github_deployment_api do %>
      <%= form.check_box :use_github_deployment_api %>
      Use GitHub Deployment API [beta]
    <% end %>
  </div>
</fieldset>

<script>
  $(document).ready(function() {
    $('#commands').sortable();
    $.fn.editableform.buttons = <%= render('commands/buttons').inspect.html_safe %>;

    $('#commands pre.local').editable({
      mode: 'inline',
      send: 'always',
      toggle: 'dblclick',
      highlight: false,
      params: function(params) {
        return { command: { command: params.value } };
      },
      ajaxOptions: {
        type: 'PATCH',
        dataType: 'json'
      }
    });

    $('#commands pre.global').dblclick(function(){
      var $warning = $('<div class="cannot-edit">Global commands cannot be edited inline, use the Admin UI.</div>')
      $(this).after($warning);
      $warning.fadeOut(3000);
      return false;
    });

    $('#commands').on('click', '.editable-destroy', function(event) {
      var editable = $(this).closest('div.col-lg-8').children('.pre-command');

      if(confirm('Are you sure you would like to remove this command from all stages?')) {
        $.ajax({
          method: 'DELETE',
          dataType: 'json',
          url: editable.data('url'),
          success: function() {
            editable.closest('.row').fadeOut();
          }
        });
      }

      event.preventDefault();
    });
  });
</script>

app/views/stages/_form.html.erb
<%= form_for [project, stage], html: { class: "form-horizontal" } do |form| %>
  <fieldset>
    <%= render 'stages/fields', form: form %>
  </fieldset>

  <hr>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <button type="submit" class="btn btn-default">Save</button>
    </div>
  </div>
<% end %>

app/views/stages/edit.html.erb
<% content_for(:page_title, "Editing #{@stage.name} (#{@project.name})") %>

<%= breadcrumb @project, @stage %>

<h1>Edit stage</h1>

<section>
  <%= render 'form', project: @project, stage: @stage %>
</section>

app/views/stages/index.html.erb
<%= render 'projects/header', project: @project, tab: "stages" %>

<section class="tabs">
  <ul id="stages" data-url="<%= reorder_project_stages_path(@project) %>" data-sortable="<%= current_user.is_admin? %>">
    <% @stages.each.with_index do |stage, index| %>
      <li class="stage-bar bar list-unstyled clearfix<%= ' sortable' if current_user.is_admin? %>" data-id="stage_id_<%= stage.id %>">
        <%= link_to stage.name, project_stage_path(@project, stage) %>
        <% if stage.locked? %>
          <span class="label label-warning" title="<%= stage.lock.summary %>"><%= lock_icon %> Locked</span>
        <% end %>
        <div class="btn-group pull-right">
          <% if current_user.is_admin? %>
            <%= link_to "Clone", clone_project_stage_path(@project, stage), class: "btn btn-default" %>
          <% end %>
          <%= deploy_link @project, stage %>
        </div>
      </li>
    <% end %>
  </ul>

  <% if current_user.is_admin? %>
    <%= link_to "Add Stage", new_project_stage_path(@project), class: "btn btn-default" %>
  <% end %>

  <button id="error_message" class="messages btn btn-danger" disabled>
    Failed to save
  </button>

  <button id="success_message" class="messages btn btn-success" disabled>
    Saved
  </button>
</section>

app/views/stages/new.html.erb
<h1>Add a stage to <%= @project.name %></h1>

<section>
  <%= render 'form', project: @project, stage: @stage %>
</section>

app/views/stages/show.html.erb
<% content_for :page_title, "#{@stage.name} - #{@project.name}" %>

<%= breadcrumb @project, @stage %>

<% if @stage.locked? %>
 <div class="alert alert-warning">Deployments to this stage were locked by <%= @stage.lock.user.name %> <%= time_ago_in_words(@stage.lock.created_at) %> ago. <%= @stage.lock.reason %></div>
<% end %>

<h1>
  <%= @stage.name %>
  <%= image_tag project_stage_path(@project, @stage, format: :svg, token: Rails.application.config.samson.badge_token), title: "Deploy badge" %>
</h1>

<section>
  <h2>Actions</h2>
  <div>
    <%= deploy_link @project, @stage %>
    <% if @stage.locked? %>
      <%= link_to project_stage_lock_path(@project, @stage), class: 'btn btn-default', method: :delete do %>
        <%= lock_icon %> Unlock
      <% end %>
    <% else %>
      <button class="btn btn-default want-lock"><%= lock_icon %> Lock</button>
      <%= form_tag project_stage_lock_path(@project, @stage), method: :post, class: 'before-lock' do %>
        <input type="text" name="description" class="lock-description" placeholder="Description">
        <button type="submit" class="do-lock btn btn-warning">Lock</button>
      <% end %>
    <% end %>

    <% if current_user.is_admin? %>
      <%= link_to "Edit stage", edit_project_stage_path(@project, @stage), class: "btn btn-default" %>
      <%= link_to project_stage_path(@project, @stage), class: 'btn btn-danger', method: :delete, data: { confirm: "Are you sure?" } do %>
        <i class="glyphicon glyphicon-remove"></i> Delete
      <% end %>
    <% end %>
  </div>

  <h2>Command</h2>
  <pre class="pre-command"><%= @stage.command %></pre>

  <h2>Recent deploys</h2>
  <table class="table">
    <thead>
      <tr>
        <th>When</th>
        <th>Who</th>
        <th>Status</th>
      </tr>
    </thead>
    <tbody>
      <%= render partial: "/projects/deploy", collection: @deploys %>
    </tbody>
  </table>
  <%= paginate @deploys %>
</section>